#!/bin/bash
# =============================================================================
#  setup_alsa_loopback.sh
#  Configures the ALSA loopback device for tapping RIM-Lite audio.
#  Called by install.sh when audio_source = alsa.
#
#  What this does:
#    1. Loads the snd-aloop kernel module
#    2. Makes it persistent across reboots
#    3. Writes /etc/asound.conf to split RIM-Lite audio to both
#       Asterisk and the loopback (where multimon-ng reads from)
#    4. Prompts you to update your Asterisk channel driver config
# =============================================================================
set -e

ASOUND_CONF="/etc/asound.conf"
MODULES_FILE="/etc/modules"          # Debian/Ubuntu
MODULES_LOAD_DIR="/etc/modules-load.d"  # systemd (Arch/HamVoIP)

# ── Detect RIM-Lite card number ───────────────────────────────────────────────
echo ""
echo "  Detecting audio devices..."
echo ""
arecord -l 2>/dev/null || true
echo ""

read -rp "  Enter the card number for your RIM-Lite / USB audio device: " RIMCARD
read -rp "  Enter the device number (usually 0): " RIMDEV

if [[ -z "$RIMCARD" || -z "$RIMDEV" ]]; then
    echo "  [ERROR] Card/device number required."
    exit 1
fi

# ── Load snd-aloop ────────────────────────────────────────────────────────────
echo ""
echo "  Loading snd-aloop kernel module..."
modprobe snd-aloop || {
    echo "  [ERROR] Failed to load snd-aloop. Check kernel module availability."
    exit 1
}

# Make persistent
if [ -d "$MODULES_LOAD_DIR" ]; then
    # systemd style (Arch/HamVoIP)
    echo "snd-aloop" > "${MODULES_LOAD_DIR}/snd-aloop.conf"
    echo "  ✓ Module persistence: ${MODULES_LOAD_DIR}/snd-aloop.conf"
elif [ -f "$MODULES_FILE" ]; then
    # Debian style
    if ! grep -q "snd-aloop" "$MODULES_FILE"; then
        echo "snd-aloop" >> "$MODULES_FILE"
        echo "  ✓ Module persistence: ${MODULES_FILE}"
    fi
fi

# ── Find loopback card number ─────────────────────────────────────────────────
LOOPCARD=$(arecord -l 2>/dev/null | grep -i loopback | head -1 | grep -oP 'card \K\d+' || echo "")
if [[ -z "$LOOPCARD" ]]; then
    echo "  [ERROR] Could not detect Loopback card number. Is snd-aloop loaded?"
    exit 1
fi
echo "  ✓ Loopback card detected: card ${LOOPCARD}"

# ── Write /etc/asound.conf ────────────────────────────────────────────────────
if [ -f "$ASOUND_CONF" ]; then
    cp "$ASOUND_CONF" "${ASOUND_CONF}.bak.$(date +%s)"
    echo "  Existing ${ASOUND_CONF} backed up"
fi

cat > "$ASOUND_CONF" << EOF
# =============================================================
#  /etc/asound.conf — EAS Monitor ALSA loopback configuration
#  Generated by eas-asl-monitor setup_alsa_loopback.sh
#  RIM-Lite: hw:${RIMCARD},${RIMDEV}   Loopback: hw:${LOOPCARD}
# =============================================================

# The loopback read side — this is what multimon-ng reads from
pcm.eas_tap {
    type hw
    card ${LOOPCARD}
    device 1
    subdevice 0
}

ctl.eas_tap {
    type hw
    card ${LOOPCARD}
}

# The splitter — mirrors RIM-Lite capture to Asterisk AND the loopback
pcm.rimlite_split {
    type plug
    slave.pcm {
        type multi
        slaves {
            a {
                pcm "hw:${RIMCARD},${RIMDEV}"
                channels 1
            }
            b {
                pcm "hw:${LOOPCARD},0,0"
                channels 1
            }
        }
        bindings {
            0 { slave a channel 0 }
            1 { slave b channel 0 }
        }
    }
}

ctl.rimlite_split {
    type hw
    card ${RIMCARD}
}
EOF

echo "  ✓ Written: ${ASOUND_CONF}"

# ── Asterisk config reminder ──────────────────────────────────────────────────
echo ""
echo "  ┌─────────────────────────────────────────────────────────────────┐"
echo "  │  MANUAL STEP REQUIRED — Asterisk channel driver config          │"
echo "  │                                                                  │"
echo "  │  You must update your chan_simpleusb.conf or chan_usbradio.conf  │"
echo "  │  to point to the 'rimlite_split' virtual device instead of      │"
echo "  │  the direct hardware device.                                     │"
echo "  │                                                                  │"
echo "  │  The exact key depends on your driver. Look for a line like:    │"
echo "  │    input_device = hw:${RIMCARD},${RIMDEV}                              │"
echo "  │  and change it to:                                               │"
echo "  │    input_device = rimlite_split                                  │"
echo "  │                                                                  │"
echo "  │  Then reload Asterisk: asterisk -rx \"module reload\"             │"
echo "  └─────────────────────────────────────────────────────────────────┘"

# ── Verify loopback ───────────────────────────────────────────────────────────
echo ""
echo "  Testing loopback device (will record 2 seconds of silence/noise)..."
if timeout 3 arecord -D eas_tap -r 22050 -f S16_LE -c 1 -t raw -q /dev/null 2>/dev/null; then
    echo "  ✓ Loopback capture device is accessible"
else
    echo "  ⚠ Could not read from loopback device — check ALSA config"
    echo "    Try: arecord -D eas_tap -r 22050 -f S16_LE -c 1 -d 2 /tmp/test.wav"
fi
echo ""
